### ISSUE TITLE
[Feature Request] Outside/on ship.

### ISSUE THREAD

**Issue by PenIsSticky** [kennyhngo/LethalCompany-NightVision#3]
Add option to make it work outside or on the ship like this mod?
https://thunderstore.io/c/lethal-company/p/Hexiez/Night_Vision_LC/
I'd use that one but the key isn't configurable and it's green instead of clear.

**Comment by kennyhngo** [comment]
Yeah, I was looking into some ways into doing that, might take a while since being able to see outside is dependent on the sun

**Comment by kennyhngo** [comment]
I have just pushed a new version! I will close this issue this Saturday if no new issues arise. I have had a few friends test it and it should be working. Be on the lookout for the new thunderstore update and let me know if you're satisfied with it.  There are some minor tweaks I need to fix but hopefully this is what you were expecting.

**Comment by smilepeak** [comment]
I hope there is a configuration option to turn off external brightness because it's a bit too bright for me. I just need the internal NightVision, and every time the spaceship descends, it will be very dazzling. Although I have already lowered the brightness to 2000, I have to set the Default Behavior to true, so this is very confusing for me
